version: '3.9'
services:
  frontend-app:
    image: node:14
    working_dir: /usr/frontend-app
    volumes:
      - .:/usr/frontend-app
    ports:
      - '5000:5000'
    command: bash -c 'yarn && yarn start'
