version: '3.9'
services:
  backend-app:
    image: node:16
    working_dir: /usr/backend-app
    volumes:
      - .:/usr/backend-app
    ports:
      - '3000:3000'
    command: bash -c 'yarn && yarn start' 